# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    # Triggers the workflow on push for the "main" branch or version tags
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        # os: [ubuntu-22.04, windows-2022]  # Define two OS targets
        os: [ubuntuwindows-2022]  # Define two OS targets

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}  # Use the matrix variable for the OS

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Echo ref name
        shell: bash
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo version: ${GITHUB_REF_NAME#v}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: bash
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
