# Build OpenSceneGraph (OSG) libraries for esmini on supported platforms

name: CI

on:
  push:
    # Triggers the workflow on push for the "main" branch or version tags
    branches:
      - '**'
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  USE_TMATE: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-22.04, windows-2022, macos-14]
        os: [macos-14]

    runs-on: ${{ matrix.os }}  # Use the matrix variable for the OS

    steps:
      # Add this step where you want execution to pause for debugging
      - name: Setup Upterm Session
        uses: owenthereal/action-upterm@v1
        with:
          ## Optional: Restrict SSH access only to your GitHub user's public SSH keys
          wait-timeout-minutes: 15
