# Build OpenSceneGraph (OSG) libraries for esmini on supported platforms

name: CI

on:
  push:
    # Triggers the workflow on push for the "main" branch or version tags
    branches:
      - '**'
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]

    runs-on: ${{ matrix.os }}  # Use the matrix variable for the OS

    steps:
      # Checks-out your repository in case we need it for debugging
      - uses: actions/checkout@v3

      - name: Install Mesa3D - Windows
        if: runner.os == 'Windows'
        uses: ssciwr/setup-mesa-dist-win@v1
        with:
          version: '22.3.5'

      - name: Install wglinfo - Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: curl.exe -L --output wglinfo64.exe --url https://github.com/gkv311/wglinfo/releases/download/22_03/wglinfo64.exe

      - name: Output wglinfo - Windows
        if: runner.os == 'Windows'
        shell: cmd
        env:
          GALLIUM_DRIVER: llvmpipe
        run: wglinfo64

      - name: Debugging with tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
        